export const PricngData = [
    {
        id: 1,
        pack: "Basic Pack",
        text1: "3 HD video lessons & tutorials",
        text2: "1 Official exam",
        text3: "100 Practice questions",
        text4: "1 Month subscriptions",
        text5: "1 Free book",
        text6: "Practice quizes & assignments",
        textQizil1: "Practice quizes & assignments",
        textQizil2: "In depth explanations",
        textQizil1: "Personal instructor Assitance",
    },
    {
        id: 2,
        pack: "Standard Pack",
        text1: "8 HD video lessons & tutorials",
        text2: "2 Official exam",
        text3: "200 Practice questions",
        text4: "1 Month subscriptions",
        text5: "3 Free books",
        text6: "Practice quizes & assignments",
        textQizil2: "In depth explanations",
        textQizil1: "Personal instructor Assitance",
    },
    {
        id: 3,
        pack: "Premium Pack",
        text1: "15 HD video lessons & tutorials",
        text2: "1 Official exam",
        text3: "100 Practice questions",
        text4: "1 Month subscriptions",
        text5: "1 Free book",
        text6: "Practice quizes & assignments",
        text7: "In depth explanations",
        text8: "Personal instructor Assitance",
        textQizil2: "In depth explanations",
        textQizil1: "Personal instructor Assitance",
    },
]